/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

//import modelo.TrabajadorLogic;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ConexionAux;
import pojo.Trabajador;

/**
 *
 * @author Hydex
 */
public class TrabajadorView extends javax.swing.JPanel {

    /**
     * Creates new form Trabajador
     */
    public TrabajadorView() {
        initComponents();
        llenar_tabla();
    }

     private void llenar_tabla()
            {
      ConexionAux conectar = new ConexionAux();//La ConexionAux tiene que mejorarse termina ni bien entra al sistema 
       Statement st =conectar.conectar();// o asi son siempre las conexiones de ser asi se tendria que hacer una llamado enc ada accion 
     try {
 //Para establecer el modelo al JTable
 DefaultTableModel modelo = new DefaultTableModel();
 this.jTable1.setModel(modelo);
 //Para conectarnos a nuestra base de datos
 modelo.ConexionAux conex=new modelo.ConexionAux();//Para ejecutar la consulta
 Statement s = conex.conectar();
 //Ejecutamos la consulta que escribimos en la caja de texto
 //y los datos lo almacenamos en un ResultSet
 ResultSet rs = s.executeQuery("select dniEmp, nomEmp,apePatEmp,apeMatEmp from Empleado");////////////En vez de Contraseña deberia de ser apellido  nombres
 //Obteniendo la informacion de las columnas que estan siendo consultadasfa
 ResultSetMetaData rsMd = rs.getMetaData();
 //La cantidad de columnas que tiene la consulta
 int cantidadColumnas = rsMd.getColumnCount();
 //Establecer como cabezeras el nombre de las colimnas
 for (int i = 1; i <= cantidadColumnas; i++) {
  modelo.addColumn(rsMd.getColumnLabel(i));
 }
 //Creando las filas para el JTable
 while (rs.next()) {
  Object[] fila = new Object[cantidadColumnas];
  for (int i = 0; i < cantidadColumnas; i++) {
    fila[i]=rs.getObject(i+1);
  }
  modelo.addRow(fila);
 }
 rs.close();
 //conexion.class.close();
} catch (Exception ex) {
 ex.printStackTrace();
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registroEmpleado = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cNombre = new javax.swing.JTextField();
        cApellidoPaterno = new javax.swing.JTextField();
        cApellidoMaterno = new javax.swing.JTextField();
        cDireccion = new javax.swing.JTextField();
        cDistrito = new javax.swing.JTextField();
        cEmail = new javax.swing.JTextField();
        cTelefono = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        masculino = new javax.swing.JRadioButton();
        femenino = new javax.swing.JRadioButton();
        registrarEmpleado = new javax.swing.JButton();
        cancelarEmpleado = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cDNI = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        modificarEmpleado = new javax.swing.JFrame();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cmNombre = new javax.swing.JTextField();
        cmApellidoPaterno = new javax.swing.JTextField();
        cmApellidoMaterno = new javax.swing.JTextField();
        cmDireccion = new javax.swing.JTextField();
        cmDistrito = new javax.swing.JTextField();
        cmEmail = new javax.swing.JTextField();
        cmTelefono = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        masculino1 = new javax.swing.JRadioButton();
        femenino1 = new javax.swing.JRadioButton();
        botonModificarEmpleado = new javax.swing.JButton();
        cancelarmEmpleado = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        cmDNI = new javax.swing.JTextField();
        bCargar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        registrarUsuario = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonEliminarEmpleado = new javax.swing.JButton();

        jLabel3.setText("Registrar Usuario");

        jLabel4.setText("Nombre *");

        jLabel5.setText("Apellido Paterno *");

        jLabel6.setText("Apellido Materno *");

        jLabel7.setText("Sexo");

        jLabel9.setText("Direccion");

        jLabel10.setText("Distrito");

        jLabel11.setText("Email");

        jLabel12.setText("Telefono");

        jLabel13.setText("Direccion");

        masculino.setText("M");

        femenino.setText("F");

        registrarEmpleado.setText("Registrar");
        registrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEmpleadoActionPerformed(evt);
            }
        });

        cancelarEmpleado.setText("Cancelar");
        cancelarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarEmpleadoActionPerformed(evt);
            }
        });

        jLabel8.setText("DNI *");

        javax.swing.GroupLayout registroEmpleadoLayout = new javax.swing.GroupLayout(registroEmpleado.getContentPane());
        registroEmpleado.getContentPane().setLayout(registroEmpleadoLayout);
        registroEmpleadoLayout.setHorizontalGroup(
            registroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroEmpleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelarEmpleado)
                .addGap(18, 18, 18)
                .addComponent(registrarEmpleado)
                .addGap(23, 23, 23))
            .addGroup(registroEmpleadoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(registroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addGroup(registroEmpleadoLayout.createSequentialGroup()
                        .addGroup(registroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(registroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registroEmpleadoLayout.createSequentialGroup()
                                .addComponent(masculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(femenino)))))
                .addGap(30, 30, 30))
        );
        registroEmpleadoLayout.setVerticalGroup(
            registroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroEmpleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(masculino)
                    .addComponent(femenino))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(24, 24, 24)
                .addGroup(registroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(registroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarEmpleado)
                    .addComponent(cancelarEmpleado)))
        );

        jLabel14.setText("Registrar Usuario");

        jLabel15.setText("Nombre *");

        jLabel16.setText("Apellido Paterno *");

        jLabel17.setText("Apellido Materno *");

        jLabel18.setText("Sexo");

        jLabel19.setText("Direccion");

        jLabel20.setText("Distrito");

        jLabel21.setText("Email");

        jLabel22.setText("Telefono");

        jLabel23.setText("Direccion");

        masculino1.setText("M");

        femenino1.setText("F");

        botonModificarEmpleado.setText("Modificar");
        botonModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarEmpleadoActionPerformed(evt);
            }
        });

        cancelarmEmpleado.setText("Cancelar");
        cancelarmEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarmEmpleadoActionPerformed(evt);
            }
        });

        jLabel24.setText("DNI *");

        bCargar.setText("Cargar");
        bCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modificarEmpleadoLayout = new javax.swing.GroupLayout(modificarEmpleado.getContentPane());
        modificarEmpleado.getContentPane().setLayout(modificarEmpleadoLayout);
        modificarEmpleadoLayout.setHorizontalGroup(
            modificarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarEmpleadoLayout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(cancelarmEmpleado)
                .addGap(18, 18, 18)
                .addComponent(botonModificarEmpleado)
                .addGap(23, 23, 23))
            .addGroup(modificarEmpleadoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(modificarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addGroup(modificarEmpleadoLayout.createSequentialGroup()
                        .addGroup(modificarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(modificarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(modificarEmpleadoLayout.createSequentialGroup()
                                .addComponent(masculino1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(femenino1))
                            .addGroup(modificarEmpleadoLayout.createSequentialGroup()
                                .addComponent(cmDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(30, 30, 30))
        );
        modificarEmpleadoLayout.setVerticalGroup(
            modificarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarEmpleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modificarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cmDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modificarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cmNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modificarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cmApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modificarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cmApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modificarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(masculino1)
                    .addComponent(femenino1))
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modificarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cmDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modificarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cmDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modificarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cmTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(modificarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonModificarEmpleado)
                    .addComponent(cancelarmEmpleado)))
        );

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("EMPLEADOS");

        jLabel2.setText("Buscar");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        registrarUsuario.setText("Registrar");
        registrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarUsuarioActionPerformed(evt);
            }
        });

        botonModificar.setText("Modificar");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonEliminarEmpleado.setText("Eliminar");
        botonEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registrarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarEmpleado))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEmpleadoActionPerformed
        // TODO add your handling code here:
        Trabajador trabajador;// = new Trabajador(
        
        Trabajador tb = new Trabajador(0);
        tb.setDniEmpleado(cDNI.getText());
        tb.setNomEmp(cNombre.getText() );
        tb.setApePatEmp(cApellidoPaterno.getText());
        tb.setApeMatEmp(cApellidoMaterno.getText());
        tb.setDirEmp(cDireccion.getText());
        tb.setDisEmp(cDistrito.getText());
        tb.setEmaEmp(cEmail.getText());
        tb.setTelEmp(cTelefono.getText());
        //tb.setSexEmp();
        //Trabajador tb = new Trabajador(0,"123456","Ed","Cornejo","Mayta");
        
       // tb.Registrar();
        
     //   registrarEmpleado.setVisible(false);
        
        int confirmado = JOptionPane.showConfirmDialog(null,"¿Lo confirmas?");

           if(cDNI.getText().length()>2 &&cNombre.getText().length()>2&&cApellidoPaterno.getText().length()>2 ){     
                if (JOptionPane.OK_OPTION == confirmado){
                    tb.Registrar();
                    llenar_tabla();
                    JOptionPane.showMessageDialog(null,"Usuario Creado");
                    this.llenar_tabla();
                    registroEmpleado.setVisible(false);
                         
                         
                         
                       
                   }
                else
                         JOptionPane.showMessageDialog(null,"Error al ingresar a la Base de datos!");
           }
           else
                         JOptionPane.showMessageDialog(null,"LLene los datos con asteriscos minimamente!");
        //TrabajadorLogic tb;
        
    }//GEN-LAST:event_registrarEmpleadoActionPerformed

    private void registrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarUsuarioActionPerformed
        // TODO add your handling code here:
         cDNI.setText("");
        cNombre.setText("");
        cApellidoPaterno.setText("");
        cApellidoMaterno.setText("");
        cDireccion.setText("");
        cDistrito.setText("");
        cEmail.setText("");
        cTelefono.setText("");
        registroEmpleado.setVisible(true);
        registroEmpleado.setSize(450, 500);
    }//GEN-LAST:event_registrarUsuarioActionPerformed

    private void cancelarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarEmpleadoActionPerformed
        // TODO add your handling code here:
            registroEmpleado.setVisible(false);
    }//GEN-LAST:event_cancelarEmpleadoActionPerformed

    private void botonEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarEmpleadoActionPerformed
        // TODO add your handling code here:
        String usuario;
           // TODO add your handling code here:
        ConexionAux conectar = new ConexionAux();//La ConexionAux tiene que mejorarse termina ni bien entra al sistema
        Statement st =conectar.conectar();// o asi son siempre las conexiones de ser asi se tendria que hacer una llamado enc ada accion
        usuario =jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        int confirmado = JOptionPane.showConfirmDialog(null,"Advertencia!\nConfirma eliminar el Empleado?");

        if (JOptionPane.OK_OPTION == confirmado){

            try
            {

                int cambioExitoso = st.executeUpdate("DELETE FROM Empleado WHERE dniEmp='"+usuario+"'");

                if(cambioExitoso==1){
                    JOptionPane.showMessageDialog(null, "Operacion Exitosa\n");
                    this.llenar_tabla();

                }
                else{
                    JOptionPane.showMessageDialog(null, "Sucedio un error no se pudo concretar el cambio\nVuelva a intentarlo mas tarde\no comuniquese con el administrador!");

                   // System.exit(0);
                }

                st.close();
            }
            catch (Exception e)
            {
                System.out.println("Error01");
                e.printStackTrace();
            }
        }
        else
        JOptionPane.showMessageDialog(null, "No se continuo con la accion!");
    }//GEN-LAST:event_botonEliminarEmpleadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String usuario="";
             String ele = jTextField1.getText();
         
        for (int i = 0; i < jTable1.getRowCount(); i++) {
          for(int j=0; j< jTable1.getColumnCount(); j++){  
            if (jTable1.getValueAt(i, j).equals(ele)) {
                jTable1.changeSelection(i, j, false, false);/////////// el i deberia de repsentar la columna
              usuario =(String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);//(jTable1.getSelectedRow(), jTable1.getSelectedColumn())
              ////////////////////////////////////////////////////////////////////////////////////////// Deberia de quedar asi pero como solo trabajamos mediante el id le ponemos 0
             
                break;
                
            }
           
          }
        }
        
        if (usuario==null)
            JOptionPane.showMessageDialog(null,"No se encontro coincidencias\nIntente de nuevo");
       
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        // TODO add your handling code here:
        cmDNI.setText("");
        cmNombre.setText("");
        cmApellidoPaterno.setText("");
        cmApellidoMaterno.setText("");
        cmDireccion.setText("");
        cmDistrito.setText("");
        cmEmail.setText("");
        cmTelefono.setText("");
         modificarEmpleado.setVisible(true);
         modificarEmpleado.setSize(450, 500);
       
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarEmpleadoActionPerformed
        // TODO add your handling code here:
          Trabajador trabajador;// = new Trabajador(
        
        Trabajador tb = new Trabajador(0);
        tb.setDniEmpleado(cmDNI.getText());
        tb.setNomEmp(cmNombre.getText() );
        tb.setApePatEmp(cmApellidoPaterno.getText());
        tb.setApeMatEmp(cmApellidoMaterno.getText());
        tb.setDirEmp(cmDireccion.getText());
        tb.setDisEmp(cmDistrito.getText());
        tb.setEmaEmp(cmEmail.getText());
        tb.setTelEmp(cmTelefono.getText());
        //tb.setSexEmp();
        //Trabajador tb = new Trabajador(0,"123456","Ed","Cornejo","Mayta");
        
       // tb.Registrar();
        
     //   registrarEmpleado.setVisible(false);
        
        int confirmado = JOptionPane.showConfirmDialog(null,"¿Lo confirmas?");

           if(cmDNI.getText().length()>2 &&cmNombre.getText().length()>2&&cmApellidoPaterno.getText().length()>2 ){     
                if (JOptionPane.OK_OPTION == confirmado){
                    if(verificado){
                        tb.Actualizar(idUsuario);
                        verificado = false;
                        llenar_tabla();
                        JOptionPane.showMessageDialog(null,"Usuario Modificado");

                    }
                    else
                        JOptionPane.showMessageDialog(null,"No verifico al usuario");
                                      // this.llenar_tabla();
                    registroEmpleado.setVisible(false);
                         
                         
                         
                       
                   }
                else
                         JOptionPane.showMessageDialog(null,"Error al ingresar a la Base de datos!");
           }
           else
                         JOptionPane.showMessageDialog(null,"LLene los datos con asteriscos minimamente!");
        //TrabajadorLogic tb;
    }//GEN-LAST:event_botonModificarEmpleadoActionPerformed

    private void cancelarmEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarmEmpleadoActionPerformed
        // TODO add your handling code here:
        modificarEmpleado.setVisible(false);
    }//GEN-LAST:event_cancelarmEmpleadoActionPerformed

    private void bCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCargarActionPerformed
        // TODO add your handling code here:
              idUsuario = cmDNI.getText();
              
            ConexionAux conectar = new ConexionAux();//La ConexionAux tiene que mejorarse termina ni bien entra al sistema 
            Statement st =conectar.conectar();// o asi son siempre las conexiones de ser asi se tendria que hacer una llamado enc ada accion 
             try
            {
              
                   ResultSet rsSeg= st.executeQuery("SELECT * FROM Empleado WHERE dniEmp='"+idUsuario+"'");
                   if(rsSeg.next() ==true){
                   //    rsSeg=st.executeQuery("SELECT nombres FROM empleadosHMS WHERE id_empleado='"+CodigoEmpleado+"'");
                       verificado = true;
                     //  campoNombresAp1.setText(rsSeg.getString("apellido_p")+" "+rsSeg.getString("apellido_m")+", "+rsSeg.getString("nombres"));     
                       //campoDoc1.setText(rsSeg.getString("dnipassaporte_empleado"));
                       cmDNI.setText(idUsuario);
                       cmNombre.setText(rsSeg.getString("nomEmp"));
                       cmApellidoPaterno.setText(rsSeg.getString("apePatEmp"));
                       cmApellidoMaterno.setText(rsSeg.getString("apeMatEmp"));
                       cmDireccion.setText(rsSeg.getString("dirEmp"));
                       cmDistrito.setText(rsSeg.getString("disEmp"));
                       cmEmail.setText(rsSeg.getString("emaEmp"));
                       cmTelefono.setText(rsSeg.getString("telEmp"));
                      // JOptionPane.showMessageDialog(null,"el codigo es valido");
                     
                   }
                   else{
                         JOptionPane.showMessageDialog(null,"Codigo no valido");
                       
                   }
                  
                        System.out.println(rsSeg);
                        
                  
                     rsSeg.close();
             }
            catch (Exception e)
            {
                   e.printStackTrace();
             }
    }//GEN-LAST:event_bCargarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCargar;
    private javax.swing.JButton botonEliminarEmpleado;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonModificarEmpleado;
    private javax.swing.JTextField cApellidoMaterno;
    private javax.swing.JTextField cApellidoPaterno;
    private javax.swing.JTextField cDNI;
    private javax.swing.JTextField cDireccion;
    private javax.swing.JTextField cDistrito;
    private javax.swing.JTextField cEmail;
    private javax.swing.JTextField cNombre;
    private javax.swing.JTextField cTelefono;
    private javax.swing.JButton cancelarEmpleado;
    private javax.swing.JButton cancelarmEmpleado;
    private javax.swing.JTextField cmApellidoMaterno;
    private javax.swing.JTextField cmApellidoPaterno;
    private javax.swing.JTextField cmDNI;
    private javax.swing.JTextField cmDireccion;
    private javax.swing.JTextField cmDistrito;
    private javax.swing.JTextField cmEmail;
    private javax.swing.JTextField cmNombre;
    private javax.swing.JTextField cmTelefono;
    private javax.swing.JRadioButton femenino;
    private javax.swing.JRadioButton femenino1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JRadioButton masculino1;
    private javax.swing.JFrame modificarEmpleado;
    private javax.swing.JButton registrarEmpleado;
    private javax.swing.JButton registrarUsuario;
    private javax.swing.JFrame registroEmpleado;
    // End of variables declaration//GEN-END:variables
    String idUsuario;
    boolean verificado=false;
}
