/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import modelo.EmpleadoLogic;
import pojo.Empleado;
import pojo.Pedido;
import modelo.PedidoLogic;
import pojo.ItemPedido;
/**
 *
 * @author geank
 */
public class VentasView extends javax.swing.JPanel {

    /**
     * Creates new form VentasView
     */
    JFrame frame;
    AddProductView apv;
    AddPedidoView apedv;
    RealizarVentasView rvv;
    EmpleadoLogic empleadologic;
    PedidoLogic pedidologic;
    Empleado empleado;
    int count;
    public VentasView() {
        empleadologic= new EmpleadoLogic();
        pedidologic=new PedidoLogic();
        empleado=empleadologic.getEmpleado(1);
        initComponents();
        codUserLabel.setText(String.valueOf(empleado.getIdEmp()));
        nombreUserLabel.setText(String.valueOf(empleado.getNomEmp()));
        iniButtons();
        Date ahora = new Date();
        dateChooser.setDate(ahora);
        
        Date dt=dateChooser.getDate();
        SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
        String currentTime = sdf.format(dt);
        iniTabla(currentTime);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        optionPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        sellButton = new javax.swing.JButton();
        detailButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pedidoTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        fechaButton = new javax.swing.JButton();
        userPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codUserLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreUserLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cargoUserLabel = new javax.swing.JLabel();

        contentPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contentPanel.setName("contentPanel"); // NOI18N

        optionPanel.setName("optionPanel"); // NOI18N

        addButton.setText("Agregar");
        addButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addButton.setName("addButton"); // NOI18N
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Eliminar");
        deleteButton.setName("deleteButton"); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Editar");
        editButton.setName("editButton"); // NOI18N
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        sellButton.setText("Venta");
        sellButton.setName("sellButton"); // NOI18N
        sellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtonActionPerformed(evt);
            }
        });

        detailButton.setText("Detalles");
        detailButton.setName("detailButton"); // NOI18N
        detailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(detailButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(detailButton)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tablePanel.setName("tablePanel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        pedidoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Num. Pedido", "Cliente", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pedidoTable.setName("pedidoTable"); // NOI18N
        jScrollPane1.setViewportView(pedidoTable);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel4.setText("Lista de pedidos:");
        jLabel4.setName("jLabel4"); // NOI18N

        dateChooser.setName("dateChooser"); // NOI18N

        fechaButton.setText("Ir");
        fechaButton.setName("fechaButton"); // NOI18N
        fechaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fechaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 328, Short.MAX_VALUE))
                .addContainerGap())
        );

        userPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userPanel.setName("userPanel"); // NOI18N

        jLabel1.setText("Usuario:");
        jLabel1.setName("jLabel1"); // NOI18N

        codUserLabel.setBackground(new java.awt.Color(130, 125, 193));
        codUserLabel.setText("Usuario 1");
        codUserLabel.setName("codUserLabel"); // NOI18N

        jLabel3.setText("Nombre:");
        jLabel3.setName("jLabel3"); // NOI18N

        nombreUserLabel.setText("usuario nombre");
        nombreUserLabel.setName("nombreUserLabel"); // NOI18N

        jLabel2.setText("Cargo:");
        jLabel2.setName("jLabel2"); // NOI18N

        cargoUserLabel.setText("Admin/Vendedor");
        cargoUserLabel.setName("cargoUserLabel"); // NOI18N

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addComponent(codUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreUserLabel)))
                .addGap(58, 58, 58)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cargoUserLabel)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codUserLabel)
                    .addComponent(nombreUserLabel)
                    .addComponent(cargoUserLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void iniButtons(){
        ImageIcon[] iconos={new ImageIcon("icons/add.jpeg"),
            new ImageIcon("icons/delete.jpeg"),new ImageIcon("icons/edit.jpeg"),
            new ImageIcon("icons/sell.jpeg")};
        addButton.setIcon(iconos[0]);
        deleteButton.setIcon(iconos[1]);
        editButton.setIcon(iconos[2]);
        sellButton.setIcon(iconos[3]);
    }
    private void iniTabla(String fecha){
        ArrayList<Pedido> listapedido=pedidologic.getPedidoFecha(fecha);
        DefaultTableModel temp =(DefaultTableModel) pedidoTable.getModel();
        
        for(Pedido pedido: listapedido){
            String estado;
            if(pedido.getEstado()==0){
                estado="pendiente";
                Object temps[]={new Boolean(false),pedido.getIdeped(),pedido.getNomPed(),estado};
                temp.addRow(temps);
            }
        }
        pedidoTable.setModel(temp);
        
    }
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
          
        apedv=new AddPedidoView();
        apedv.setEmpleado(empleado);
        
        final JFrame frameNewPedido=new JFrame();
        frameNewPedido.setContentPane(apedv);
        frameNewPedido.setVisible(true);
        frameNewPedido.setSize(780,500);
        
        frame=(JFrame)SwingUtilities.getAncestorOfClass(JFrame.class,this);
        frame.setEnabled(false);
        
        frameNewPedido.addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent we){
                    frame.setEnabled(true);
                    if(apedv.presionButtonSave)
                        actualizarTabla();
                    frameNewPedido.dispose();
                }
        });
        /**/
    }//GEN-LAST:event_addButtonActionPerformed
    public void actualizarTabla(){
        Pedido pedido=pedidologic.getUltimoPedido();
        DefaultTableModel temp =(DefaultTableModel) pedidoTable.getModel();
        String estado;
        if(pedido.getEstado()==0)
            estado="pendiente";
        else estado="realizado";
        Object[] fila={new Boolean(false),pedido.getIdeped(),pedido.getNomPed(),estado};
        temp.addRow(fila);
        pedidoTable.setModel(temp);
        count++;
    }
    public void actualizarTabla(ArrayList<Pedido> listpedido){
        DefaultTableModel model = (DefaultTableModel) pedidoTable.getModel();
        for(Pedido pedido: listpedido){
            String estado= pedido.getEstado()==0?"pendiente":"realizado";              
            Object temp[]={new Boolean(false),pedido.getIdeped(),pedido.getNomPed(),estado};
            model.addRow(temp);
        }
        pedidoTable.setModel(model);
    }
    public void actualizarDato(){
        String msm=apv.mostrar();
        System.out.println(msm);
    }
    private void sellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtonActionPerformed
        // TODO add your handling code here:
        //RealizarVentaView rvv=new RealizarVentaView();
        //rvv.setVisible(true);
        final DefaultTableModel model=(DefaultTableModel)pedidoTable.getModel();
        final int row=pedidoTable.getSelectedRow();
        
        if(row==-1)
            JOptionPane.showMessageDialog(null,"Tiene que seleccionar un pedido que no este activo");
        else{
            String estadoPed=(String)model.getValueAt(row,3);
            if(estadoPed.equals("realizado")){
                JOptionPane.showMessageDialog(null,"Se culmino la venta de ese pedido");
                return;
            };
            rvv=new RealizarVentasView();
            int idPed=(Integer)model.getValueAt(row,1);
            ArrayList<ItemPedido> listItemPed= pedidologic.getDetallePedido(idPed);
            rvv.updateCampos(listItemPed,idPed);
            final JFrame frameNewRealizarVentas=new JFrame();
            frameNewRealizarVentas.setContentPane(rvv);
            frameNewRealizarVentas.setVisible(true);
            frameNewRealizarVentas.setSize(800,700);

            frame=(JFrame)SwingUtilities.getAncestorOfClass(JFrame.class,this);
            frame.setEnabled(false);

            frameNewRealizarVentas.addWindowListener(new WindowAdapter(){
                    public void windowClosing(WindowEvent we){
                        frame.setEnabled(true);
                        if(rvv.presionButtonSave){
                          model.setValueAt("realizado",row,3);
                        }
                        //actualizarEstado();
                        frameNewRealizarVentas.dispose();
                    }
            });
        }
        
    }//GEN-LAST:event_sellButtonActionPerformed

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_addButtonMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)pedidoTable.getModel();
        int row=pedidoTable.getSelectedRow();
        if(row==-1)
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
        else{
            int idePed=(Integer)model.getValueAt(row,1);
            Pedido pedidoa=pedidologic.getPedido(idePed);
            if(pedidoa.getEstado()==1){
                JOptionPane.showMessageDialog(null, "El pedido seleccionado no se puede editar, pruebe con detalles");
                return;
            }
            apedv=new AddPedidoView();
            apedv.setEmpleado(empleado);
            apedv.setNumPedLabel(String.valueOf(idePed));
            apedv.isUpdate=true;
            ArrayList<ItemPedido> listitems=pedidologic.getDetallePedido(idePed);
            apedv.actualizarTablaPedido(listitems,pedidoa.getNomPed(),String.valueOf(pedidoa.getNuroMesPed()));
            final JFrame frameNewPedido=new JFrame();
            frameNewPedido.setContentPane(apedv);
            frameNewPedido.setVisible(true);
            frameNewPedido.setSize(780,500);
            frame=(JFrame)SwingUtilities.getAncestorOfClass(JFrame.class,this);
            frame.setEnabled(false);
            frameNewPedido.addWindowListener(new WindowAdapter(){
                    public void windowClosing(WindowEvent we){
                        frame.setEnabled(true);
                        if(apedv.presionButtonSave)
                            actualizarTabla();
                        frameNewPedido.dispose();
                    }
            });
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void fechaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
        ArrayList<Pedido> listped=pedidologic.getPedidoFecha(sdf.format(dateChooser.getDate()));
        limpiarTabla();
        actualizarTabla(listped);
    }//GEN-LAST:event_fechaButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)pedidoTable.getModel();
        int row=model.getRowCount();
        ArrayList<Integer> filasParaEliminar=new ArrayList<Integer>();
        boolean error=false;
        for(int i=0;i<row;i++){
            String estado=(String) model.getValueAt(i,3);
            if((Boolean)model.getValueAt(i,0) && estado.equals("pendiente")){
                int idePed=(Integer)model.getValueAt(i,1);
                pedidologic.eliminarPedido(idePed);
                filasParaEliminar.add(idePed);
            }
            else if((Boolean)model.getValueAt(i,0) && estado.equals("realizado")){
                error=true;
            }
        }
        if(error)JOptionPane.showMessageDialog(null,"no se puede eliminar pedido realizado");
        else{
            try{
                int size=filasParaEliminar.size();
                for(int i=0;i<size;i++){
                    model=(DefaultTableModel)pedidoTable.getModel();
                    boolean borrar=false;
                    int j=0;
                    while(!borrar){
                        if((Integer)model.getValueAt(j,1)==filasParaEliminar.get(i)){
                            borrar=true;
                            model.removeRow(j);
                        }
                        j++;
                    }
                }
                JOptionPane.showMessageDialog(null,"Se elimino correctamente el pedido");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error al actualizar la tabla");
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void limpiarTabla(){
        //resultTable.remove//
        DefaultTableModel modelo=(DefaultTableModel)pedidoTable.getModel();
        try{
            int filas=modelo.getRowCount();
            System.out.println("numero de filas: "+filas);
            for(int i=0;i<filas;i++)
                modelo.removeRow(0);
        }
        catch(Exception e){
            System.out.println("Este es el error: "+e.getMessage());
            JOptionPane.showMessageDialog(null,"Error al limpiar la tabla");
        }
    }
    private void detailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)pedidoTable.getModel();
        int row=pedidoTable.getSelectedRow();
        if(row==-1)
        {
            JOptionPane.showMessageDialog(null,"Tienes que escoger algun pedido ralizado");
            return;
        }
        String estado=(String)model.getValueAt(row,3);
        if(estado.equals("pendiente")){
            JOptionPane.showMessageDialog(null,"El pedido aun no se ha cobrado");
            return;
        }
        int idePed=(Integer)model.getValueAt(row,1);
        apedv=new AddPedidoView();
        apedv.setEmpleado(empleado); 
        apedv.isUpdate=true;
        Pedido pedidoa=pedidologic.getPedido(idePed);
        ArrayList<ItemPedido> listitems=pedidologic.getDetallePedido(idePed);
        apedv.actualizarTablaPedido(listitems,pedidoa.getNomPed(),String.valueOf(pedidoa.getNuroMesPed()));
        final JFrame frameNewPedido=new JFrame();
        frameNewPedido.setContentPane(apedv);
        frameNewPedido.setVisible(true);
        frameNewPedido.setSize(780,500);
        frame=(JFrame)SwingUtilities.getAncestorOfClass(JFrame.class,this);
        frame.setEnabled(false);
        frameNewPedido.addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent we){
                    frame.setEnabled(true);
                    if(apedv.presionButtonSave)
                        actualizarTabla();
                    frameNewPedido.dispose();
                }
        });   
    }//GEN-LAST:event_detailButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel cargoUserLabel;
    private javax.swing.JLabel codUserLabel;
    private javax.swing.JPanel contentPanel;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton detailButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton fechaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreUserLabel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JTable pedidoTable;
    private javax.swing.JButton sellButton;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
