/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventas;
import java.awt.event.KeyEvent;
import javax.swing.UIManager;
import modelo.*;

/**
 *
 * @author Hydex
 */
public class Main extends javax.swing.JFrame {

    /**
     * Matahambre managment system 
     */
    public Main() {
        initComponents();
        Dialog_login.setTitle("Inicio de Sesión");
        Dialog_login.setSize(400, 220);
        Dialog_login.setLocationRelativeTo(this);
        Dialog_login.setVisible(true);
        
        
        Dialog_password.setTitle("Primera Sesion - Configuracion");
        Dialog_password.setSize(500, 220);
        Dialog_password.setLocationRelativeTo(this);
        Dialog_password.setVisible(false);
        
        terminalID="Pc01";
        terminalID= System.getProperty("user.name")+"-PC";
        System.out.print("******" + terminalID);
        intento=0;
        this.setLocation(250,30);
        nro_tabs=jTabbedPane.getTabCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_login = new javax.swing.JDialog();
        bn_login_cerrar = new javax.swing.JButton();
        tf_login_contraseña = new javax.swing.JPasswordField();
        bn_login_ingresar = new javax.swing.JButton();
        lb_login_contraseña = new javax.swing.JLabel();
        tf_login_usuario = new javax.swing.JTextField();
        lb_login_titulo = new javax.swing.JLabel();
        lb_login_usuario = new javax.swing.JLabel();
        Dialog_password = new javax.swing.JDialog();
        lb_pass_contraseña = new javax.swing.JLabel();
        tf_pass_vrf_nue_contraseña = new javax.swing.JPasswordField();
        tf_pass_nue_contraseña = new javax.swing.JPasswordField();
        lb_pass_nue_contraseña = new javax.swing.JLabel();
        lb_pass_titulo = new javax.swing.JLabel();
        jb_password_cambiar = new javax.swing.JButton();
        jb_password_cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jToolBar1 = new javax.swing.JToolBar();
        jTabbedPane = new javax.swing.JTabbedPane();
        inicio1 = new vista.Inicio();
        administrador1 = new vista.Administrador();
        ventasView2 = new vista.VentasView();
        reportes2 = new vista.Reportes();
        cajaView2 = new vista.CajaView();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        Dialog_login.setResizable(false);

        bn_login_cerrar.setText("Cerrar");
        bn_login_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_login_cerrarActionPerformed(evt);
            }
        });

        tf_login_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_login_contraseñaActionPerformed(evt);
            }
        });
        tf_login_contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_login_contraseñaEnter_goto_jb_login_ingresar(evt);
            }
        });

        bn_login_ingresar.setText("Ingresar");
        bn_login_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_login_ingresarActionPerformed(evt);
            }
        });

        lb_login_contraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lock_24px.png"))); // NOI18N
        lb_login_contraseña.setText("Contraseña");

        tf_login_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_login_usuarioEnter_goto_tcontra(evt);
            }
        });

        lb_login_titulo.setText("MMS-Inicio Sesion");

        lb_login_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Client_Male_Light_24px.png"))); // NOI18N
        lb_login_usuario.setText("Usuario");

        javax.swing.GroupLayout Dialog_loginLayout = new javax.swing.GroupLayout(Dialog_login.getContentPane());
        Dialog_login.getContentPane().setLayout(Dialog_loginLayout);
        Dialog_loginLayout.setHorizontalGroup(
            Dialog_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_loginLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(Dialog_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_loginLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(bn_login_ingresar)
                        .addGap(42, 42, 42)
                        .addComponent(bn_login_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_login_titulo)
                    .addGroup(Dialog_loginLayout.createSequentialGroup()
                        .addGroup(Dialog_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_login_usuario)
                            .addComponent(lb_login_contraseña))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Dialog_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_login_usuario)
                            .addComponent(tf_login_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        Dialog_loginLayout.setVerticalGroup(
            Dialog_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_loginLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lb_login_titulo)
                .addGap(18, 18, 18)
                .addGroup(Dialog_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_login_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_login_usuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dialog_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_login_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_login_contraseña))
                .addGap(18, 18, 18)
                .addGroup(Dialog_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bn_login_cerrar)
                    .addComponent(bn_login_ingresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lb_pass_contraseña.setText("Nueva Contraseña");

        tf_pass_vrf_nue_contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_pass_vrf_nue_contraseñaEnter_goto_jb_password_cambiar(evt);
            }
        });

        tf_pass_nue_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pass_nue_contraseñaActionPerformed(evt);
            }
        });
        tf_pass_nue_contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Enter_goto_tf_pass_nue_contraseñaVerific(evt);
            }
        });

        lb_pass_nue_contraseña.setText("Verifique Contraseña");

        lb_pass_titulo.setText("Bienvenido al Sistema MMS");

        jb_password_cambiar.setText("Cambiar Contraseña");
        jb_password_cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_password_cambiarActionPerformed(evt);
            }
        });

        jb_password_cancelar.setText("Cancelar");
        jb_password_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_password_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_passwordLayout = new javax.swing.GroupLayout(Dialog_password.getContentPane());
        Dialog_password.getContentPane().setLayout(Dialog_passwordLayout);
        Dialog_passwordLayout.setHorizontalGroup(
            Dialog_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_passwordLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(Dialog_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog_passwordLayout.createSequentialGroup()
                        .addComponent(jb_password_cambiar)
                        .addGap(18, 18, 18)
                        .addComponent(jb_password_cancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog_passwordLayout.createSequentialGroup()
                        .addGroup(Dialog_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_pass_nue_contraseña)
                            .addComponent(lb_pass_contraseña))
                        .addGap(48, 48, 48)
                        .addGroup(Dialog_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_pass_nue_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_pass_vrf_nue_contraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog_passwordLayout.createSequentialGroup()
                        .addComponent(lb_pass_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        Dialog_passwordLayout.setVerticalGroup(
            Dialog_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_passwordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_pass_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(Dialog_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_pass_nue_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_pass_contraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dialog_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_pass_vrf_nue_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_pass_nue_contraseña))
                .addGap(18, 18, 18)
                .addGroup(Dialog_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_password_cancelar)
                    .addComponent(jb_password_cambiar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                validacion_acceso(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                time_log(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                get_acceso(evt);
            }
        });

        jToolBar1.setRollover(true);

        jTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane.setOpaque(true);
        jTabbedPane.setPreferredSize(new java.awt.Dimension(800, 600));
        jTabbedPane.addTab("Inicio", inicio1);
        jTabbedPane.addTab("Administrador", new javax.swing.ImageIcon(getClass().getResource("/img/Customer_Male_Light_48px.png")), administrador1); // NOI18N
        jTabbedPane.addTab("Ventas", new javax.swing.ImageIcon(getClass().getResource("/img/Additional money.png")), ventasView2); // NOI18N
        jTabbedPane.addTab("Reportes", new javax.swing.ImageIcon(getClass().getResource("/img/graph_chart_1.png")), reportes2); // NOI18N
        jTabbedPane.addTab("Caja", new javax.swing.ImageIcon(getClass().getResource("/img/dolar.png")), cajaView2); // NOI18N

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void tf_pass_vrf_nue_contraseñaEnter_goto_jb_password_cambiar(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pass_vrf_nue_contraseñaEnter_goto_jb_password_cambiar
        // TODO add your handling code here:
        if(evt.getKeyCode ()== KeyEvent.VK_ENTER) //saltar al jb_password_cambiar
        {
            jb_password_cambiar.doClick();
        }
    }//GEN-LAST:event_tf_pass_vrf_nue_contraseñaEnter_goto_jb_password_cambiar

    private void tf_pass_nue_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pass_nue_contraseñaActionPerformed

    }//GEN-LAST:event_tf_pass_nue_contraseñaActionPerformed

    private void Enter_goto_tf_pass_nue_contraseñaVerific(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Enter_goto_tf_pass_nue_contraseñaVerific
        // TODO add your handling code here:
        if(evt.getKeyCode ()== KeyEvent.VK_ENTER) //saltar al siguiente text field
        {
            tf_pass_vrf_nue_contraseña.grabFocus();
        }
    }//GEN-LAST:event_Enter_goto_tf_pass_nue_contraseñaVerific

    private void jb_password_cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_password_cambiarActionPerformed

        //VENTANA REESTABLECER CONTRASEÑA
        re_password=tf_pass_nue_contraseña.getText();
        vf_password=tf_pass_vrf_nue_contraseña.getText();
        seguridad_ingreso.restablecerPassword(re_password, vf_password);
        // Se activan y desactivan las ventanas correspondientes

        Dialog_login.setVisible(seguridad_ingreso.isDialog_loginVISIBLE());
        Dialog_password.setVisible(seguridad_ingreso.isDialog_passwordVISBLE());
        this.setVisible(seguridad_ingreso.isThisVISIBLE());
        if(seguridad_ingreso.isSystemEXIT())
        System.exit(0);
    }//GEN-LAST:event_jb_password_cambiarActionPerformed

    private void jb_password_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_password_cancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jb_password_cancelarActionPerformed

    private void tf_login_usuarioEnter_goto_tcontra(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_login_usuarioEnter_goto_tcontra
        // TODO add your handling code here:
        if(evt.getKeyCode ()== KeyEvent.VK_ENTER) //saltar al siguiente text field
        {
            tf_login_contraseña.grabFocus();
        }
    }//GEN-LAST:event_tf_login_usuarioEnter_goto_tcontra

    private void bn_login_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_login_ingresarActionPerformed

        //VENTANA LOGIN

        usuario=tf_login_usuario.getText();
        password=tf_login_contraseña.getText();
        seguridad_ingreso = new Seguridad (usuario,password,terminalID);
        
        seguridad_ingreso.verificacionSistema();
        // Se activan y desactivan las ventanas correspondientes

        Dialog_login.setVisible(seguridad_ingreso.isDialog_loginVISIBLE());
        Dialog_password.setVisible(seguridad_ingreso.isDialog_passwordVISBLE());
        this.setVisible(seguridad_ingreso.isThisVISIBLE());
        if(seguridad_ingreso.isSystemEXIT())
        System.exit(0);
    }//GEN-LAST:event_bn_login_ingresarActionPerformed

    private void tf_login_contraseñaEnter_goto_jb_login_ingresar(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_login_contraseñaEnter_goto_jb_login_ingresar
        // TODO add your handling code here:
        if(evt.getKeyCode ()== KeyEvent.VK_ENTER)  //saltar al jb_login_ingresar
        {
            bn_login_ingresar.doClick();
            tf_login_usuario.grabFocus();
        }
    }//GEN-LAST:event_tf_login_contraseñaEnter_goto_jb_login_ingresar

    private void tf_login_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_login_contraseñaActionPerformed

    }//GEN-LAST:event_tf_login_contraseñaActionPerformed

    private void bn_login_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_login_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bn_login_cerrarActionPerformed

    private void get_acceso(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_get_acceso
        // TODO add your handling code here:
    }//GEN-LAST:event_get_acceso

    private void time_log(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_time_log
        // TODO add your handling code here:
        System.out.println ("todo  fin ");
        seguridad_ingreso.finSesion();
    }//GEN-LAST:event_time_log

    private void validacion_acceso(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_validacion_acceso
        // TODO add your handling code here:
        this.NivelAccesos();
    }//GEN-LAST:event_validacion_acceso
    public void NivelAccesos( )
   {

       int [] tabs=seguridad_ingreso.getNivelDeAcceso(nro_tabs);
       int j=0;
       for(int i=0;i<nro_tabs;i++)
       {
           if (tabs[i]==1){
                jTabbedPane.remove(j);
                j--; }
           j++;
   }
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
          try{
             UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
          } catch (Exception e) {
            System.err.println("Error loading L&F: " + e.getMessage());
          } 
          
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog_login;
    private javax.swing.JDialog Dialog_password;
    private javax.swing.JMenuItem aboutMenuItem;
    private vista.Administrador administrador1;
    private javax.swing.JButton bn_login_cerrar;
    private javax.swing.JButton bn_login_ingresar;
    private vista.CajaView cajaView2;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private vista.Inicio inicio1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jb_password_cambiar;
    private javax.swing.JButton jb_password_cancelar;
    private javax.swing.JLabel lb_login_contraseña;
    private javax.swing.JLabel lb_login_titulo;
    private javax.swing.JLabel lb_login_usuario;
    private javax.swing.JLabel lb_pass_contraseña;
    private javax.swing.JLabel lb_pass_nue_contraseña;
    private javax.swing.JLabel lb_pass_titulo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private vista.Reportes reportes2;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JPasswordField tf_login_contraseña;
    private javax.swing.JTextField tf_login_usuario;
    private javax.swing.JPasswordField tf_pass_nue_contraseña;
    private javax.swing.JPasswordField tf_pass_vrf_nue_contraseña;
    private vista.VentasView ventasView2;
    // End of variables declaration//GEN-END:variables
    String usuario;
    String password;
    
    int intento;
    int nro_tabs;
    String terminalID;
    Seguridad seguridad_ingreso;
    String re_password, vf_password;
}
